// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAftib8OED0MjKljGnOy0PlVTq7xvwHE60',
    appId: '1:940588297434:web:3a2bc37306880dada309e3',
    messagingSenderId: '940588297434',
    projectId: 'shopping-app-5395c',
    authDomain: 'shopping-app-5395c.firebaseapp.com',
    storageBucket: 'shopping-app-5395c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuPMSLwrnsn78iXH3_BKdm3EiCcCegnx4',
    appId: '1:940588297434:android:8b16aeb8d8626eb0a309e3',
    messagingSenderId: '940588297434',
    projectId: 'shopping-app-5395c',
    storageBucket: 'shopping-app-5395c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-aKCl8qO_j2C53UGCnzmY27mL2hYcX4g',
    appId: '1:940588297434:ios:a7dcbf0e54fd6026a309e3',
    messagingSenderId: '940588297434',
    projectId: 'shopping-app-5395c',
    storageBucket: 'shopping-app-5395c.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-aKCl8qO_j2C53UGCnzmY27mL2hYcX4g',
    appId: '1:940588297434:ios:a7dcbf0e54fd6026a309e3',
    messagingSenderId: '940588297434',
    projectId: 'shopping-app-5395c',
    storageBucket: 'shopping-app-5395c.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAftib8OED0MjKljGnOy0PlVTq7xvwHE60',
    appId: '1:940588297434:web:5a50f3ec21f3d319a309e3',
    messagingSenderId: '940588297434',
    projectId: 'shopping-app-5395c',
    authDomain: 'shopping-app-5395c.firebaseapp.com',
    storageBucket: 'shopping-app-5395c.appspot.com',
  );

}